/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CTC_RPC_H_RPCGEN
#define _CTC_RPC_H_RPCGEN

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#define FAL_PORT_CTRL_PATH  "/tmp/fal_port_ctrl"
#define OPTOE_E2P_DATA_LEN  512

enum ctc_rpc_port_speed_auto
{
    CTC_RPC_PORT_SPEED_AUTO_EN = 0,
    CTC_RPC_PORT_SPEED_AUTO_DIS = 1,
};
typedef enum ctc_rpc_port_speed_auto ctc_rpc_port_speed_auto_e;

enum ctc_rpc_port_optoe_type
{
    CTC_RPC_OPTOE_TYPE_SFP = 0,
    CTC_RPC_OPTOE_TYPE_QSFP = 1,
};
typedef enum ctc_rpc_port_optoe_type ctc_rpc_port_optoe_type_e;

enum ctc_rpc_linkagg_type
{
    CTC_RPC_LINKAGG_HASH = 0,
    CTC_RPC_LINKAGG_ROUND = 1,
};
typedef enum ctc_rpc_linkagg_type ctc_rpc_linkagg_type_e;



enum ctc_rpc_port_speed_e {
	CTC_RPC_PORT_SPEED_1G = 0,
	CTC_RPC_PORT_SPEED_100M = 1,
	CTC_RPC_PORT_SPEED_10M = 2,
	CTC_RPC_PORT_SPEED_2G5 = 3,
	CTC_RPC_PORT_SPEED_10G = 4,
	CTC_RPC_PORT_SPEED_20G = 5,
	CTC_RPC_PORT_SPEED_40G = 6,
	CTC_RPC_PORT_SPEED_100G = 7,
	CTC_RPC_PORT_SPEED_5G = 8,
	CTC_RPC_PORT_SPEED_25G = 9,
	CTC_RPC_PORT_SPEED_50G = 10,
	CTC_RPC_PORT_SPEED_MAX = 11,
};
typedef enum ctc_rpc_port_speed_e ctc_rpc_port_speed_e;

enum ctc_rpc_port_if_type_e {
	CTC_RPC_PORT_IF_NONE = 0,
	CTC_RPC_PORT_IF_SGMII = 0 + 1,
	CTC_RPC_PORT_IF_2500X = 0 + 2,
	CTC_RPC_PORT_IF_QSGMII = 0 + 3,
	CTC_RPC_PORT_IF_USXGMII_S = 0 + 4,
	CTC_RPC_PORT_IF_USXGMII_M2G5 = 0 + 5,
	CTC_RPC_PORT_IF_USXGMII_M5G = 0 + 6,
	CTC_RPC_PORT_IF_XAUI = 0 + 7,
	CTC_RPC_PORT_IF_DXAUI = 0 + 8,
	CTC_RPC_PORT_IF_XFI = 0 + 9,
	CTC_RPC_PORT_IF_KR = 0 + 10,
	CTC_RPC_PORT_IF_CR = 0 + 11,
	CTC_RPC_PORT_IF_KR2 = 0 + 12,
	CTC_RPC_PORT_IF_CR2 = 0 + 13,
	CTC_RPC_PORT_IF_KR4 = 0 + 14,
	CTC_RPC_PORT_IF_CR4 = 0 + 15,
	CTC_RPC_PORT_IF_FX = 0 + 16,
	CTC_RPC_PORT_IF_MAX_TYPE = 0 + 17,
};
typedef enum ctc_rpc_port_if_type_e ctc_rpc_port_if_type_e;

enum ctc_rpc_stats_mode_e {
	CTC_RPC_STATS_MODE_PLUS = 0,
	CTC_RPC_STATS_MODE_DETAIL = 1,
	CTC_RPC_STATS_MODE_NUM = 2,
};
typedef enum ctc_rpc_stats_mode_e ctc_rpc_stats_mode_e;

enum ctc_rpc_mac_stats_dir_e {
	CTC_RPC_STATS_MAC_STATS_RX = 0,
	CTC_RPC_STATS_MAC_STATS_TX = 1,
	CTC_RPC_STATS_MAC_STATS_MAX = 2,
};
typedef enum ctc_rpc_mac_stats_dir_e ctc_rpc_mac_stats_dir_e;


enum ctc_api_opt_e {
	CTC_API_SPEED_SET = 1,
	CTC_API_ENABLE_SET = 2,
	CTC_API_STATUS_GET = 3,
	CTC_API_TXRX_GET = 4,
    CTC_API_AUTO_SET = 5,
    CTC_API_OPTOE_GET = 6,
    CTC_API_AGG_HASH_SET = 7,
    CTC_API_AGG_HASH_GET = 8,
	CTC_API_KEEPALIVE,
};

enum ctc_api_link_status_e
{
    CTC_PORT_LINK_DOWN = 0,
    CTC_PORT_LINK_up = 1,
 };
typedef enum ctc_api_opt_e ctc_api_opt_e;


struct ctc_rpc_optoe_info
{
    uint8_t optoe_stats;
    ctc_rpc_port_optoe_type_e optoe_type;
    uint8_t e2p_data[OPTOE_E2P_DATA_LEN];
};
typedef struct ctc_rpc_optoe_info ctc_rpc_optoe_info_s;

struct ctc_rpc_port_s {
	uint8_t lchip;
	uint32_t gport;
};
typedef struct ctc_rpc_port_s ctc_rpc_port_s;

struct ctc_rpc_port_if_mode_s {
	ctc_rpc_port_speed_e speed;
	ctc_rpc_port_if_type_e interface_type;
};
typedef struct ctc_rpc_port_if_mode_s ctc_rpc_port_if_mode_s;

struct ctc_rpc_if_mode_opt_s {
	ctc_rpc_port_s port_id;
	ctc_rpc_port_if_mode_s port_mode;
};
typedef struct ctc_rpc_if_mode_opt_s ctc_rpc_if_mode_opt_s;


struct ctc_rpc_if_status_info_s {
	uint8_t link_status;
	uint8_t speed;
	uint8_t autoneg;
};
typedef struct ctc_rpc_if_status_info_s ctc_rpc_if_status_info_s;


struct ctc_socket_trans_info_set_s
{
    uint8_t opt;
	ctc_rpc_port_s port_id;
    ctc_rpc_port_if_mode_s speed_mode;
    uint8_t enable;
    uint8_t auto_enable;
	ctc_rpc_mac_stats_dir_e dir;
	ctc_rpc_stats_mode_e info_mode;
    ctc_rpc_linkagg_type_e agg_type;
};
typedef struct ctc_socket_trans_info_set_s ctc_socket_trans_info_set_s;

struct ctc_rpc_stats_mac_rec_plus_s {
	uint64_t all_octets;
	uint64_t all_pkts;
	uint64_t ucast_pkts;
	uint64_t mcast_pkts;
	uint64_t bcast_pkts;
	uint64_t runts_pkts;
	uint64_t giants_pkts;
	uint64_t crc_pkts;
	uint64_t overrun_pkts;
	uint64_t pause_pkts;
	uint64_t fragments_pkts;
	uint64_t jabber_pkts;
	uint64_t jumbo_events;
	uint64_t drop_events;
	uint64_t error_pkts;
};
typedef struct ctc_rpc_stats_mac_rec_plus_s ctc_rpc_stats_mac_rec_plus_s;

struct ctc_rpc_stats_mac_snd_plus_s {
	uint64_t all_octets;
	uint64_t all_pkts;
	uint64_t ucast_pkts;
	uint64_t mcast_pkts;
	uint64_t bcast_pkts;
	uint64_t underruns_pkts;
	uint64_t jumbo_events;
	uint64_t error_pkts;
};
typedef struct ctc_rpc_stats_mac_snd_plus_s ctc_rpc_stats_mac_snd_plus_s;

struct ctc_rpc_stats_mac_rec_s {
	uint64_t good_ucast_pkts;
	uint64_t good_ucast_bytes;
	uint64_t good_mcast_pkts;
	uint64_t good_mcast_bytes;
	uint64_t good_bcast_pkts;
	uint64_t good_bcast_bytes;
	uint64_t good_pause_pkts;
	uint64_t good_pause_bytes;
	uint64_t good_normal_pause_pkts;
	uint64_t good_normal_pause_bytes;
	uint64_t good_pfc_pause_pkts;
	uint64_t good_pfc_pause_bytes;
	uint64_t good_control_pkts;
	uint64_t good_control_bytes;
	uint64_t fcs_error_pkts;
	uint64_t fcs_error_bytes;
	uint64_t mac_overrun_pkts;
	uint64_t mac_overrun_bytes;
	uint64_t good_oversize_pkts;
	uint64_t good_oversize_bytes;
	uint64_t good_undersize_pkts;
	uint64_t good_undersize_bytes;
	uint64_t good_63_pkts;
	uint64_t good_63_bytes;
	uint64_t bad_63_pkts;
	uint64_t bad_63_bytes;
	uint64_t good_1519_pkts;
	uint64_t good_1519_bytes;
	uint64_t bad_1519_pkts;
	uint64_t bad_1519_bytes;
	uint64_t good_jumbo_pkts;
	uint64_t good_jumbo_bytes;
	uint64_t bad_jumbo_pkts;
	uint64_t bad_jumbo_bytes;
	uint64_t pkts_64;
	uint64_t bytes_64;
	uint64_t pkts_65_to_127;
	uint64_t bytes_65_to_127;
	uint64_t pkts_128_to_255;
	uint64_t bytes_128_to_255;
	uint64_t pkts_256_to_511;
	uint64_t bytes_256_to_511;
	uint64_t pkts_512_to_1023;
	uint64_t bytes_512_to_1023;
	uint64_t pkts_1024_to_1518;
	uint64_t bytes_1024_to_1518;
	uint64_t pkts_1519_to_2047;
	uint64_t bytes_1519_to_2047;
	uint64_t pkts_2048_to_mtu1;
	uint64_t bytes_2048_to_mtu1;
	uint64_t pkts_mtu1_to_mtu2;
	uint64_t bytes_mtu1_to_mtu2;
};
typedef struct ctc_rpc_stats_mac_rec_s ctc_rpc_stats_mac_rec_s;

struct ctc_rpc_stats_mac_snd_s {
	uint64_t good_ucast_pkts;
	uint64_t good_ucast_bytes;
	uint64_t good_mcast_pkts;
	uint64_t good_mcast_bytes;
	uint64_t good_bcast_pkts;
	uint64_t good_bcast_bytes;
	uint64_t good_pause_pkts;
	uint64_t good_pause_bytes;
	uint64_t good_control_pkts;
	uint64_t good_control_bytes;
	uint64_t pkts_63;
	uint64_t bytes_63;
	uint64_t pkts_64;
	uint64_t bytes_64;
	uint64_t pkts_65_to_127;
	uint64_t bytes_65_to_127;
	uint64_t pkts_128_to_255;
	uint64_t bytes_128_to_255;
	uint64_t pkts_256_to_511;
	uint64_t bytes_256_to_511;
	uint64_t pkts_512_to_1023;
	uint64_t bytes_512_to_1023;
	uint64_t pkts_1024_to_1518;
	uint64_t bytes_1024_to_1518;
	uint64_t pkts_1519;
	uint64_t bytes_1519;
	uint64_t jumbo_pkts;
	uint64_t jumbo_bytes;
	uint64_t oversize_pkts;
	uint64_t oversize_bytes;
	uint64_t mac_underrun_pkts;
	uint64_t mac_underrun_bytes;
	uint64_t fcs_error_pkts;
	uint64_t fcs_error_bytes;
	uint64_t pkts_1519_to_2047;
	uint64_t bytes_1519_to_2047;
	uint64_t pkts_2048_to_mtu1;
	uint64_t bytes_2048_to_mtu1;
	uint64_t pkts_mtu1_to_mtu2;
	uint64_t bytes_mtu1_to_mtu2;
};
typedef struct ctc_rpc_stats_mac_snd_s ctc_rpc_stats_mac_snd_s;

struct ctc_rpc_mac_stats_plus_s {
	ctc_rpc_stats_mac_rec_plus_s rx_stats_plus;
	ctc_rpc_stats_mac_snd_plus_s tx_stats_plus;
};
typedef struct ctc_rpc_mac_stats_plus_s ctc_rpc_mac_stats_plus_s;

struct ctc_rpc_mac_stats_detail_s {
	ctc_rpc_stats_mac_rec_s rx_stats;
	ctc_rpc_stats_mac_snd_s tx_stats;
};
typedef struct ctc_rpc_mac_stats_detail_s ctc_rpc_mac_stats_detail_s;

struct ctc_rpc_msg_unite_s {
	ctc_rpc_mac_stats_plus_s stats_plus;
	ctc_rpc_mac_stats_detail_s stats_detail;
};
typedef struct ctc_rpc_msg_unite_s ctc_rpc_msg_unite_s;

struct ctc_rpc_mac_stats_s {
	uint8_t stats_mode;
	uint8_t rsv[3];
	ctc_rpc_msg_unite_s u;
};
typedef struct ctc_rpc_mac_stats_s ctc_rpc_mac_stats_s;

struct ctc_rpc_if_rxtx_info_s {
	ctc_rpc_port_s port_id;
	ctc_rpc_mac_stats_dir_e dir;
	ctc_rpc_stats_mode_e info_mode;
};
typedef struct ctc_rpc_if_rxtx_info_s ctc_rpc_if_rxtx_info_s;


/***********************************usr api start ********************************/
int ctc_api_init(void);
int ctc_api_uninit(void);

int ctc_api_port_speed_set(ctc_rpc_port_s *argp,ctc_rpc_port_if_mode_s *argmode);
int ctc_api_port_enable_set(ctc_rpc_port_s *argp, uint8_t enable);
ctc_rpc_if_status_info_s* ctc_api_port_status_get(ctc_rpc_port_s *argp);
ctc_rpc_mac_stats_s *ctc_api_port_rxtx_get(ctc_rpc_if_rxtx_info_s *argp);

int ctc_socket_init(void);
void ctc_socket_uninit(void);

/************************************  end    **********************************/
#ifdef __cplusplus
}
#endif

#endif /* !_CTC_RPC_H_RPCGEN */
